name: Generate E-Paper Screenshot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Stáhnutí repozitáře
        uses: actions/checkout@v4

      - name: Příprava Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Vložení tajného API klíče do HTML
        env:
          SECRET_KEY: ${{ secrets.WU_API_KEY_GITHUB }}
        run: |
          sed -i "s/__WU_API_KEY_GITHUB__/${SECRET_KEY}/g" *.html

      - name: Instalace Puppeteeru
        run: |
          mkdir -p out
          npm install puppeteer

      - name: Spuštění renderování HTML do PNG
        run: node generate_image.js

      - name: Publikace obrázků na GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
